# Your Telegram bot token
# See "https://core.telegram.org/bots#botfather"
token: ""

# Your Telegram Channel's public name - e.g. @chalkpe_status
# See "https://telegram.org/blog/channels"
defaultChannel: ""

# If it true, player chats will be broadcasted to your channel
broadcastPlayerChats: false

# If it true, link previews for links in your messages will be disabled
disableWebPagePreview: true

# If it true, Markdown syntax will be applied to your messages
# See "https://core.telegram.org/bots/api#using-markdown"
enableMarkdownParsing: false


# If it true, the plugin shows Telegram API responses to your console
debugMode: false