############################
### Basic configurations ###
############################

# Your Telegram bot's token.
# If you not have any bots, talk to @BotFather("https://core.telegram.org/bots#botfather") and create your first bot.
token: ""

# The chat_id of your Telegram group or the public name of your Telegram channel, e.g. -23612486, "@chalkpe_status".
# Note that the bot must be joined to the group or be an administrator of the channel.
# You can get your chat_id of the group by using the '/chat_id' command in there.
defaultChannel: ""

# The interval of the bot updating messages from the Telegram API.
# A second is equals to 20. If it's a negative value, the updating will be disabled.
updateInterval: 20

# TODO: Description required
minecraftUserPrefix: "~"

# TODO: Description required
telegramUserPrefix: "@"




###########################
### Link configurations ###
###########################

# Broadcasts the server's player activities to your Telegram group/channel automatically.
broadcastToTelegram: true

# Broadcasts the Telegram group's user messages to your server automatically.
broadcastTelegramMessages: true

# Handles the command messages from the Telegram, e.g. '/chat_id', '/online'
enableTelegramCommands: true

# TODO: Description required
broadcastServerStart: false



#######################################
### Advanced Bot API configurations ###
#######################################

# Disables link previews for links in your messages.
disableWebPagePreview: true

# Applies basic Markdown syntax to your messages.
# See "https://core.telegram.org/bots/api#using-markdown".
enableMarkdownParsing: false



#########################
### Developer options ###
#########################

# Shows the Telegram Bot API responses to the server console.
debugMode: false
